chrome:
  use_undetected: true
  load_profile: true
  user_data_dir: ""  # If empty, will use default
  profile_directory: "Default"  # Default value, can be customized

firefox:
  load_profile: true
  user_data_dir: ""  # If empty, will use default
  profile_directory: "Default"  # Default value, can be customized

edge:
  load_profile: true
  user_data_dir: ""  # If empty, will use default
  profile_directory: "Default"  # Default value, can be customized

chatgpt:
  url: "https://chatgpt.com/"
  chat_base_url: "https://chatgpt.com/c/"
  support_models: [""]
  input_xpath: "//textarea[@id='prompt-textarea']"
  send_button_xpath: "//button[@data-testid='send-button']"
  stop_button_xpath: "//button[@data-testid='stop-button']"
  prompt_xpath: "//div[@data-message-author-role='user']"
  response_xpath: "//div[@data-message-author-role='assistant']"
  chat_list_xpath: "//div[@data-testid='conversation-turn']"
  model_xpath: "//div[@aria-haspopup='menu' and contains(@id, 'radix-')]"
  models_menu_xpath: "//div[@data-side='bottom' and @data-align='start' and @role='menu' and @aria-orientation='vertical' and @data-state='open']"
  menu_items_relative_xpath: ".//div[@role='menuitem']"
  sidebar_xpath: "//*[@id='__next']/div/div[1]/div/div/div/div/nav/div[2]"