chrome:
  use_undetected: true
  load_profile: true
  user_data_dir: ""  # If empty, will use default
  profile_directory: "Default"  # Default value, can be customized

firefox:
  load_profile: true
  user_data_dir: ""  # If empty, will use default
  profile_directory: "Default"  # Default value, can be customized

edge:
  load_profile: true
  user_data_dir: ""  # If empty, will use default
  profile_directory: "Default"  # Default value, can be customized

chatgpt:
  url: "https://chatgpt.com/"
  chat_base_url: "https://chatgpt.com/c/"
  support_models: [""]
  input_xpath: "//textarea[@id='prompt-textarea']"
  file_xpath: "//input[@type='file']"
  send_button_xpath: "//button[@data-testid='send-button']"
  stop_button_xpath: "//button[@data-testid='stop-button']"
  prompt_xpath: "//div[@data-message-author-role='user']"
  response_xpath: "//div[@data-message-author-role='assistant']"
  chat_list_xpath: "//div[@data-testid='conversation-turn']"
  model_xpath: "//div[@aria-haspopup='menu' and contains(@id, 'radix-')]"
  models_menu_xpath: "//div[@data-side='bottom' and @data-align='start' and @role='menu' and @aria-orientation='vertical' and @data-state='open']"
  menu_items_relative_xpath: ".//div[@role='menuitem']"
  sidebar_xpath: "//*[@id='__next']/div[1]/div[1]/div/div/div/nav/div[2]"

claude:
  url: "https://claude.ai/"
  chat_base_url: "https://claude.ai/chat/"
  chat_list_url: "https://claude.ai/recents"
  support_models: [""]
  input_xpath: "//div[@aria-label='Write your prompt to Claude']//div[@contenteditable='true']"
  file_xpath: "//input[@type='file' and @data-testid='file-upload']"
  send_button_xpath: "//button[@aria-label='Send Message']"
  stop_button_xpath: "//button[@aria-label='Stop Response']"
  prompt_xpath: "//div[contains(@class, 'font-user-message')]"
  response_xpath: "//div[contains(@class, 'font-claude-message')]"
  chat_list_xpath: "//li[contains(@class, 'relative group')]"
  model_xpath: "//button[@data-testid='model-selector-dropdown']/div[1]/div[2]"
  models_menu_xpath: "//button[@data-testid='model-selector-dropdown']"