chrome:
  use_undetected: true
  load_profile: true
  user_data_dir: ""  # If empty, will use default
  profile_directory: ""  # Default value, can be customized

firefox:
  load_profile: true
  user_data_dir: ""  # If empty, will use default
  profile_directory: "Default"  # Default value, can be customized

edge:
  load_profile: true
  user_data_dir: ""  # If empty, will use default
  profile_directory: "Default"  # Default value, can be customized

chatgpt:
  url: "https://chatgpt.com/"
  chat_base_url: "https://chatgpt.com/c/"
  support_models: [""]
  input_xpath: "//div[@id='prompt-textarea']"
  file_xpath: "//input[@type='file']"
  send_button_xpath: "//button[@data-testid='send-button']"
  stop_button_xpath: "//button[@data-testid='stop-button']"
  audio_button_xpath: "//button[@data-testid='composer-speech-button']"
  prompt_xpath: "//div[@data-message-author-role='user']"
  response_xpath: "//div[@data-message-author-role='assistant']"
  chat_list_xpath: "//div[@data-testid='conversation-turn']"
  model_xpath: "(//button[@data-testid='model-switcher-dropdown-button'])[2]"
  models_menu_xpath: "//div[@data-side='bottom' and @data-align='start' and @role='menu' and @aria-orientation='vertical' and @data-state='open']"
  more_models_xpath: "//div[@data-testid='more-models-submenu' and @role='menuitem']"
  menu_items_relative_xpath: ".//div[@role='menuitem']"
  sidebar_xpath: "//div[@class='group/sidebar']"
  canvas_button_xpath: "//div[@role='button' and starts-with(@id, 'textdoc-message')]"
  canvas_title_xpath: "//header//h2"
  canvas_container_xpath: "//div[@id='codemirror' or @id='prosemirror-editor-container']"
  canvas_content_xpath: "//div[@id='codemirror' or @id='prosemirror-editor-container']//div[@translate='no']"
  code_canvas_xpath: "//div[@id='codemirror']//div[@translate='no']"
  text_canvas_xpath: "//div[@id='prosemirror-editor-container']/div[@translate='no']"
  models:
    "gpt-4o": "//div[@data-testid='model-switcher-gpt-4o' and @role='menuitem']"
    "o1": "//div[@data-testid='model-switcher-o1' and @role='menuitem']"
    "o1-mini": "//div[@data-testid='model-switcher-o1-mini' and @role='menuitem']"
    "o1-pro": "//div[@data-testid='model-switcher-o1-pro' and @role='menuitem']"
    "gpt-4o-mini": "//div[@data-testid='model-switcher-gpt-4o-mini' and @role='menuitem']"
    "gpt-4": "//div[@data-testid='model-switcher-gpt-4' and @role='menuitem']"

sora:
  url: "https://sora.com/library/"
  prefix: "https://sora.com/"
  video_base_url: "https://sora.com/g/"
  input_xpath: "//textarea[@placeholder='Describe your video...']"
  general_button_xpath: "//button[@type='button' and @role='combobox' and @aria-autocomplete='none' and @dir='ltr']"
  aspect_ratios: ["16:9", "1:1", "9:16"]
  resolutions: ["480p", "720p", "1080p"]
  durations: ["5s", "10s", "15s", "20s"]
  variations: ["1v", "2v", "4v"]
  create_button_xpath: "//button[.//span[text()='Create video']]"
  latest_video_container_xpath: "//div[@data-index='1']"
  video_href_xpath: ".//a[contains(@href, '/g/')]"
  first_download_xpath: "//button[@aria-haspopup='menu' and .//span[normalize-space(text())='Download']]"
  second_download_xpath: "//button[normalize-space(text())='Download' and not(.//span)]"
  download_option_xpath: "//div[@data-side='bottom']//div[@role='menuitem'][div[text()='Video']]"
  improve_div_xpath: ".//div[text()='Pick the best videos from this set to help improve Sora']"
  task_href_xpath: ".//a[contains(@href, '/t/task')]"
  improve_confirm_xpath: "//button[text()='Got it']"
  pick_left_video_xpath: "/html/body/div[2]/div/div[1]/div/div/div[1]/div[1]/div/div[2]"
  keep_selected_button_xpath: "//button[text()='Keep selected video']"
  keep_none_button_xpath: "//button[text()='Keep none']"
  final_none_button_xpath: "//button[text()='Cancel']/following-sibling::button[text()='Keep none']"

claude:
  url: "https://claude.ai/"
  chat_base_url: "https://claude.ai/chat/"
  chat_list_url: "https://claude.ai/recents"
  support_models: [""]
  input_xpath: "//div[@aria-label='Write your prompt to Claude']//div[@contenteditable='true']"
  file_xpath: "//input[@type='file' and @data-testid='file-upload']"
  send_button_xpath: "//button[@aria-label='Send Message']"
  stop_button_xpath: "//button[@aria-label='Stop Response']"
  file_button_xpath: "//button[@aria-label='Upload content']"
  prompt_xpath: "//div[contains(@class, 'font-user-message')]"
  response_xpath: "//div[@data-is-streaming='false']/div[contains(@class, 'font-claude-message')]"
  chat_list_xpath: "//div[contains(@class, 'relative group')]"
  model_button_xpath: "//button[@data-testid='model-selector-dropdown']"
  models_menu_xpath: "//button[@data-testid='model-selector-dropdown']"
  more_models_xpath: "//div[@role='menuitem' and @aria-haspopup='menu']"
  models_xpath: "//div[@role='menuitem' and @data-radix-collection-item]"
  model_description_xpath: "//div[@role='menuitem']//div[contains(text(), '{name}')]/../following-sibling::div[contains(text(), '{description}')]/.."
  control_button_xpath: "//button[@data-testid='chat-controls']"
  artifact_button_xpath: ".//button[@aria-label='Preview contents']"
  iframe_artifact_xpath: "/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div/iframe"
  text_artifact_xpath: "/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[3]/div/div[contains(@class, 'font-claude-message')]"
  code_artifact_xpath: "/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[3]/div/div/code"
  models:
    "sonnet": 
      name: "Claude 3.5 Sonnet"
      description: "Most intelligent model"
    "sonnet_legacy":
      name: "Claude 3.5 Sonnet (June 2024)"
      description: "Legacy model"
    "haiku":
      name: "Claude 3.5 Haiku"
      description: "Fastest model for daily tasks"
    "opus":
      name: "Claude 3 Opus"
      description: "Excels at writing and complex tasks"